version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
    depends_on:
      - postgres
      - redis
      - minio
      - coturn
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: glowchat
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    command: ["redis-server","--appendonly","yes"]
    volumes:
      - redisdata:/data
  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
    volumes:
      - miniodata:/data
  coturn:
    image: instrumentisto/coturn
    ports:
      - "3478:3478"
      - "3478:3478/udp"
    environment:
      - REALM=glowchat.local
    # For production configure turnserver.conf and secure credentials
volumes:
  pgdata:
  redisdata:
  miniodata:
